# CircleCI 2.0を指定
version: 2
jobs:
# workflowsを使わない時はjobsにbuildが必要
  build:
    environment:
#     タイムゾーンを日本時間にする
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
#     ECRのURIが長いのでここに書いておく
      REPONAME: "928622159311.dkr.ecr.ap-northeast-1.amazonaws.com"
#   Dockerコンテナ使用を宣言
    docker:
#       ECRに置いてあるDockerイメージ名（これがCircleCIのビルド環境になる）
      - image: $REPONAME/pf-dev-ecr-baseimg:latest
    steps:
#       GitHubからファイルを持ってくる
      - checkout
#       dockerコマンドを使用する場合には指定
      - setup_remote_docker
#       DockerfileでECRからイメージを取得するのでその前にAWS CLIでログイン
#       Dockerイメージをビルド
      - run:
          name: "Build docker image"
          command: |
            eval $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker build -t $REPONAME/pf-dev-ecr-webap:latest .
#       作成されたDockerイメージを起動
#       httpでPHPスクリプトが表示されるかテスト
      - run:
          name: "Display Test Page"
          command: |
            docker run -d -p 80:80 --name newwebap $REPONAME/pf-dev-ecr-webap:latest
            docker exec newwebap curl http://localhost/
#       作成されたDockerイメージをECRに保存
      - run:
          name: "Push docker image"
          command: |
            docker push $REPONAME/pf-dev-ecr-webap:latest
